name: Yemenaman
description: A new Flutter project.


publish_to: 'none' 


version: 2.0.0+2

environment:
  sdk: '>=2.18.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  splash_screen_view: ^3.0.0
  rounded_loading_button: ^2.1.0
  firebase_core: 
  firebase_auth: 
  cloud_firestore: ^3.5.0
  firebase_storage: ^10.3.10
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  xml : 
  url_launcher: ^6.1.6
  dropdown_button2: ^1.8.9
  image_picker: ^0.8.6
  tuple: ^2.0.1
  rxdart: ^0.27.6
  shared_preferences: ^2.0.15
  share_plus: ^6.3.0
  change_app_package_name: ^1.1.0
  card_swiper: ^2.0.4
  video_player: ^2.4.7
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^9.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  # following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
