// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAl9FEV36En0xTSNkyRgVuka2jLTkV0_I',
    appId: '1:980841577286:web:9a53ba8db37117ebbbc347',
    messagingSenderId: '980841577286',
    projectId: 'fight-blackmailing',
    authDomain: 'fight-blackmailing.firebaseapp.com',
    storageBucket: 'fight-blackmailing.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABx18Ae2MdUkFLs8cqXuxMafNEpy89elo',
    appId: '1:980841577286:android:c5ef21105cb4c758bbc347',
    messagingSenderId: '980841577286',
    projectId: 'fight-blackmailing',
    storageBucket: 'fight-blackmailing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQ2mNS20SgIY2f1A-RIgbHBu8JqIeBtI',
    appId: '1:980841577286:ios:2a5facdf0bf8a043bbc347',
    messagingSenderId: '980841577286',
    projectId: 'fight-blackmailing',
    storageBucket: 'fight-blackmailing.appspot.com',
    iosClientId: '980841577286-3tnkvkrseb2mjpjvedb2jbeq936nk7ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.help',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfQ2mNS20SgIY2f1A-RIgbHBu8JqIeBtI',
    appId: '1:980841577286:ios:2a5facdf0bf8a043bbc347',
    messagingSenderId: '980841577286',
    projectId: 'fight-blackmailing',
    storageBucket: 'fight-blackmailing.appspot.com',
    iosClientId: '980841577286-3tnkvkrseb2mjpjvedb2jbeq936nk7ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.help',
  );
}
